/**
 * @module domain/contracts/contract.errors
 * @description Erros e warnings serializáveis do domínio de contratos — Phase 10.2.
 */

export const CONTRACT_DOMAIN_ERROR_CODES = [
  'CONTRACT_NOT_FOUND',
  'TENANT_REQUIRED',
  'PATIENT_REQUIRED',
  'GUARDIAN_REQUIRED',
  'BUDGET_REQUIRED',
  'FINANCIAL_SNAPSHOT_REQUIRED',
  'TEMPLATE_NOT_PUBLISHED',
  'TEMPLATE_REQUIRED',
  'VERSION_REQUIRED',
  'VERSION_ALREADY_LOCKED',
  'VERSION_NOT_LOCKED',
  'INVALID_STATUS_TRANSITION',
  'CANCELLATION_REASON_REQUIRED',
  'REQUIRED_SIGNER_MISSING',
  'SIGNATURES_INCOMPLETE',
  'SIGNATURES_ALREADY_STARTED',
  'SIGNATURE_DECLINED',
  'ENVELOPE_EXPIRED',
  'LEGACY_STATUS_NOT_MAPPABLE',
  'REMOTE_STATUS_NOT_MAPPABLE',
  'DOMAIN_STATUS_NOT_MAPPABLE_TO_LEGACY',
  'TENANT_MISMATCH',
  'INVALID_DATE_RANGE',
  'INVALID_DOCUMENT_TYPE',
  'INVALID_STATUS',
  'TITLE_REQUIRED',
  'CONTRACT_NUMBER_INVALID',
  'VERSION_NUMBER_INVALID',
  'SNAPSHOT_REQUIRED',
  'APPROVALS_REQUIRED',
  'HASH_INVALID',
  'CONTENT_LOCKED',
  'TERMINAL_STATUS',
  'SUPERSEDE_REFERENCE_REQUIRED',
  'EVIDENCE_PENDING',
  'PACKAGE_INCOMPLETE',
  'INVALID_INPUT',
  'CONTRACTS_V2_STORAGE_UNAVAILABLE',
  'FEATURE_FLAG_DISABLED',
  'PERMISSION_DENIED',
  'TEMPLATE_CONTENT_EMPTY',
  'TEMPLATE_VARIABLE_UNKNOWN',
  'TEMPLATE_VARIABLE_INVALID',
  'TEMPLATE_HTML_BLOCKED',
  'TEMPLATE_CHANGE_SUMMARY_REQUIRED',
  'TEMPLATE_ALREADY_PUBLISHED',
  'TEMPLATE_ARCHIVED',
  'TEMPLATE_BLOCK_INVALID',
  'TEMPLATE_REQUIRED_BLOCK_MISSING',
  'OPTIMISTIC_CONCURRENCY_CONFLICT',
  'HASH_UNAVAILABLE',
  'IDEMPOTENCY_CONFLICT',
  'CONTENT_HASH_REQUIRED',
  'PACKAGE_INCOMPLETE_ITEMS',
  'PACKAGE_PATIENT_MISMATCH',
  'SIGNATURES_STARTED',
  'SIGNATURE_POLICY_REQUIRED',
  'SIGNATURE_METHOD_NOT_ALLOWED',
  'SIGNATURE_CAPABILITY_UNAVAILABLE',
  'SIGNATURE_ENVELOPE_NOT_FOUND',
  'SIGNATURE_ENVELOPE_NOT_ACTIVE',
  'SIGNATURE_ENVELOPE_ALREADY_TERMINAL',
  'SIGNATURE_ENVELOPE_CONFLICT',
  'SIGNATURE_SIGNER_NOT_FOUND',
  'SIGNATURE_SIGNER_OUT_OF_ORDER',
  'SIGNATURE_SIGNER_ALREADY_SIGNED',
  'SIGNATURE_REQUIRED_SIGNER_MISSING',
  'SIGNATURE_DOCUMENT_NOT_VIEWED',
  'SIGNATURE_AUTHENTICATION_REQUIRED',
  'SIGNATURE_AUTHENTICATION_FAILED',
  'SIGNATURE_CHALLENGE_EXPIRED',
  'SIGNATURE_CHALLENGE_ATTEMPTS_EXCEEDED',
  'SIGNATURE_CHALLENGE_ALREADY_CONSUMED',
  'SIGNATURE_TERMS_REQUIRED',
  'SIGNATURE_ARTIFACT_REQUIRED',
  'SIGNATURE_SESSION_INVALID',
  'SIGNATURE_SESSION_EXPIRED',
  'SIGNATURE_SESSION_REVOKED',
  'SIGNATURE_SESSION_STORAGE_UNAVAILABLE',
  'SIGNATURE_SESSION_HASH_INVALID',
  'SIGNATURE_SESSION_ALREADY_CONSUMED',
  'SIGNATURE_SESSION_PERSISTENCE_FAILED',
  'SIGNATURE_CHALLENGE_STORAGE_UNAVAILABLE',
  'SIGNATURE_CHALLENGE_PERSISTENCE_FAILED',
  'SIGNATURE_RATE_LIMIT_EXCEEDED',
  'SIGNATURE_RATE_LIMIT_STORAGE_UNAVAILABLE',
  'SIGNATURE_DELIVERY_PROVIDER_UNAVAILABLE',
  'SIGNATURE_DELIVERY_FAILED',
  'SIGNATURE_DELIVERY_RATE_LIMITED',
  'SIGNATURE_INVITATION_ALREADY_SENT',
  'SIGNATURE_INVITATION_RESEND_NOT_ALLOWED',
  'SIGNATURE_PUBLIC_ACCESS_DENIED',
  'SIGNATURE_PUBLIC_SESSION_NOT_READY',
  'SIGNATURE_PUBLIC_DOCUMENT_UNAVAILABLE',
  'SIGNATURE_PUBLIC_ACCEPTANCE_HASH_MISMATCH',
  'SIGNATURE_PUBLIC_OPERATION_CONFLICT',
  'SIGNATURE_PUBLIC_SIGNING_FAILED',
  'SIGNATURE_PUBLIC_DECLINE_FAILED',
  'SIGNATURE_HTTP_RATE_LIMIT_EXCEEDED',
  'SIGNATURE_PUBLIC_ORIGIN_NOT_ALLOWED',
  'SIGNATURE_DOCUMENT_HASH_MISMATCH',
  'SIGNATURE_EVIDENCE_HASH_REQUIRED',
  'SIGNATURE_ENVELOPE_EXPIRED',
  'SIGNATURE_DECLINE_REASON_REQUIRED',
  'SIGNATURE_IDEMPOTENCY_CONFLICT',
  'CONTRACT_RENDER_MODEL_INVALID',
  'CONTRACT_HTML_RENDER_FAILED',
  'CONTRACT_PDF_RENDERER_UNAVAILABLE',
  'CONTRACT_PDF_GENERATION_FAILED',
  'CONTRACT_PDF_TOO_LARGE',
  'CONTRACT_FILE_TYPE_NOT_ALLOWED',
  'CONTRACT_FILE_MIME_NOT_ALLOWED',
  'CONTRACT_FILE_PATH_INVALID',
  'CONTRACT_FILE_STORAGE_UNAVAILABLE',
  'CONTRACT_FILE_NOT_FOUND',
  'CONTRACT_FILE_TENANT_MISMATCH',
  'CONTRACT_FILE_INTEGRITY_INVALID',
  'CONTRACT_FILE_HASH_MISMATCH',
  'CONTRACT_FILE_SIZE_MISMATCH',
  'CONTRACT_FILE_ALREADY_VERIFIED',
  'CONTRACT_FILE_DELETE_NOT_ALLOWED',
  'CONTRACT_STORAGE_OBJECT_NOT_FOUND',
  'CONTRACT_STORAGE_OBJECT_ALREADY_EXISTS',
  'CONTRACT_STORAGE_OBJECT_HASH_CONFLICT',
  'CONTRACT_STORAGE_METADATA_INCONSISTENT',
  'CONTRACT_STORAGE_COMPENSATION_REQUIRED',
  'CONTRACT_STORAGE_BUCKET_UNAVAILABLE',
  'CONTRACT_STORAGE_POLICY_DENIED',
  'CONTRACT_FILE_RECONCILIATION_REQUIRED',
  'CONTRACTS_V2_LOCAL_STORAGE_REQUIRED',
  'CONTRACT_EVIDENCE_REPORT_HASH_MISMATCH',
  'CONTRACT_VERIFICATION_CODE_INVALID',
  'CONTRACT_SIGNED_ARTIFACTS_NOT_READY',
  'CONTRACT_SIGNATURE_EVIDENCE_INCOMPLETE',
  'CONTRACT_SIGNING_COMPLETION_NOT_READY',
  'CONTRACT_SIGNING_COMPLETION_ALREADY_DONE',
  'CONTRACT_SIGNING_COMPLETION_CONFLICT',
  'CONTRACT_SIGNED_PDF_REQUIRED',
  'CONTRACT_SIGNED_PDF_INVALID',
  'CONTRACT_EVIDENCE_REPORT_REQUIRED',
  'CONTRACT_EVIDENCE_REPORT_INVALID',
  'CONTRACT_INTEGRITY_MANIFEST_REQUIRED',
  'CONTRACT_INTEGRITY_MANIFEST_INVALID',
  'CONTRACT_LEDGER_UNAVAILABLE',
  'CONTRACT_LEDGER_SEQUENCE_CONFLICT',
  'CONTRACT_LEDGER_HASH_INVALID',
  'CONTRACT_LEDGER_CHAIN_INVALID',
  'CONTRACT_LEDGER_APPEND_FAILED',
  'CONTRACT_LEDGER_ALREADY_CONTAINS_EVENT',
  'CONTRACT_SIGNED_ARTIFACT_TENANT_MISMATCH',
  'CONTRACT_SIGNED_ARTIFACT_VERSION_MISMATCH',
  'CONTRACT_SIGNED_ARTIFACT_ENVELOPE_MISMATCH',
  'CONTRACT_SIGNED_IDEMPOTENCY_CONFLICT',
  'CONTRACT_SIGNED_ROLLBACK_FAILED',
  'CONTRACT_SIGNED_RECONCILIATION_REQUIRED',
  'CONTRACT_SIGNED_EFFECT_NOT_READY',
] as const;

export type ContractDomainErrorCode = (typeof CONTRACT_DOMAIN_ERROR_CODES)[number];

export interface ContractDomainError {
  code: ContractDomainErrorCode;
  message: string;
  field?: string;
  metadata?: Record<string, unknown>;
}

export type ContractDomainWarningCode =
  | 'LEGACY_DATA_PARTIAL'
  | 'LEGACY_STATUS_LOSSY'
  | 'LEGACY_DOCUMENT_TYPE_CUSTOM'
  | 'LEGACY_DATA_URL_ATTACHMENT'
  | 'LEGACY_ODONTOGRAM_SNAPSHOT_ABSENT'
  | 'LEGACY_STORAGE_REFERENCE_ABSENT'
  | 'LEGACY_HASH_NOT_CRYPTOGRAPHIC'
  | 'LEGACY_VERSION_NOT_LOCKED'
  | 'REMOTE_STATUS_LOSSY'
  | 'OPTIONAL_SNAPSHOT_ABSENT'
  | 'TEMPLATE_SENSITIVE_VARIABLE'
  | 'TEMPLATE_OPTIONAL_WITNESSES_ABSENT'
  | 'TEMPLATE_OPTIONAL_ODONTOGRAM_ABSENT'
  | 'TEMPLATE_CONTENT_LONG'
  | 'TEMPLATE_NO_CONTACT_VARIABLE'
  | 'TEMPLATE_CLAUSE_WITHOUT_LEGAL_REVIEW'
  | 'TEMPLATE_NO_PROCEDURE_OR_SPECIALTY';

export interface ContractDomainWarning {
  code: ContractDomainWarningCode;
  message: string;
  field?: string;
  metadata?: Record<string, unknown>;
}

export function createContractDomainError(
  code: ContractDomainErrorCode,
  message: string,
  field?: string,
  metadata?: Record<string, unknown>,
): ContractDomainError {
  return { code, message, ...(field ? { field } : {}), ...(metadata ? { metadata } : {}) };
}

export function createContractDomainWarning(
  code: ContractDomainWarningCode,
  message: string,
  field?: string,
  metadata?: Record<string, unknown>,
): ContractDomainWarning {
  return { code, message, ...(field ? { field } : {}), ...(metadata ? { metadata } : {}) };
}
