export const BUDGET_STATUS = {
  RASCUNHO: 'RASCUNHO',
  ENVIADO: 'ENVIADO',
  NEGOCIACAO: 'NEGOCIACAO',
  APROVADO: 'APROVADO',
  CONTRATO_GERADO: 'CONTRATO_GERADO',
  HISTORICO: 'HISTORICO',
  REPROVADO: 'REPROVADO',
  CANCELADO: 'CANCELADO',
};
