#!/usr/bin/env node
/**
 * PHASE_10.21X — Gera `.env.staging.local` (gitignored) a partir de
 * STAGING_* em `.env.local` + anon key staging.
 *
 * NÃO imprime secrets. NÃO commit. Fail-closed se production.
 *
 * Usage:
 *   STAGING_SUPABASE_ANON_KEY=... node scripts/staging/prepareStagingBrowserEnv.mjs
 *   # ou com STAGING_SUPABASE_ANON_KEY já em .env.local
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '../..');
const STAGING_REF = 'tckdjyunwmdpqmewrwvt';
const PRODUCTION_REF = 'uoepkwhqztmsjnzirpev';
const OUT = path.join(ROOT, '.env.staging.local');

function parseEnvFile(filePath) {
  const env = {};
  if (!fs.existsSync(filePath)) return env;
  for (const line of fs.readFileSync(filePath, 'utf8').split(/\n/)) {
    if (!line || line.trim().startsWith('#') || !line.includes('=')) continue;
    const i = line.indexOf('=');
    env[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  return env;
}

function refOf(url) {
  try {
    return new URL(url).host.split('.')[0];
  } catch {
    return null;
  }
}

function main() {
  const dotenv = parseEnvFile(path.join(ROOT, '.env.local'));
  const url = process.env.STAGING_SUPABASE_URL || dotenv.STAGING_SUPABASE_URL || '';
  const service =
    process.env.STAGING_SUPABASE_SERVICE_ROLE_KEY
    || dotenv.STAGING_SUPABASE_SERVICE_ROLE_KEY
    || '';
  const anon =
    process.env.STAGING_SUPABASE_ANON_KEY
    || dotenv.STAGING_SUPABASE_ANON_KEY
    || process.env.VITE_STAGING_SUPABASE_ANON_KEY
    || '';

  if (!url || !service || !anon) {
    console.error(JSON.stringify({
      ok: false,
      error: 'MISSING_STAGING_CREDENTIALS',
      need: ['STAGING_SUPABASE_URL', 'STAGING_SUPABASE_SERVICE_ROLE_KEY', 'STAGING_SUPABASE_ANON_KEY'],
    }));
    process.exit(2);
  }

  const ref = refOf(url);
  if (ref !== STAGING_REF) {
    console.error(JSON.stringify({ ok: false, error: 'URL_NOT_STAGING', ref }));
    process.exit(2);
  }
  if (String(url).includes(PRODUCTION_REF) || String(service).includes(PRODUCTION_REF)) {
    console.error(JSON.stringify({ ok: false, error: 'PRODUCTION_REF_DETECTED' }));
    process.exit(2);
  }

  const platformKey = process.env.PLATFORM_API_KEY || dotenv.PLATFORM_API_KEY || '';

  const body = `# AUTO-GENERATED by scripts/staging/prepareStagingBrowserEnv.mjs — DO NOT COMMIT
# PHASE_10.21X isolated staging browser smoke
VITE_STAGING_TEST_MODE=true
LOVE_ODONTO_STAGING_TEST_MODE=1
STAGING_TEST_MODE=1

SUPABASE_URL=${url}
SUPABASE_SERVICE_ROLE_KEY=${service}
SUPABASE_ANON_KEY=${anon}
STAGING_SUPABASE_URL=${url}
STAGING_SUPABASE_SERVICE_ROLE_KEY=${service}
STAGING_SUPABASE_ANON_KEY=${anon}

VITE_SUPABASE_PLATFORM_URL=${url}
VITE_SUPABASE_PLATFORM_ANON_KEY=${anon}
VITE_SUPABASE_APP_URL=${url}
VITE_SUPABASE_APP_ANON_KEY=${anon}
VITE_SUPABASE_URL=${url}
VITE_SUPABASE_ANON_KEY=${anon}
VITE_SUPABASE_PROJECT_REF=${STAGING_REF}
VITE_CONSOLE_SUPABASE_URL=${url}
VITE_CONSOLE_SUPABASE_ANON_KEY=${anon}

# API local staging-safe (nunca Railway production)
VITE_PLATFORM_API_BASE_URL=http://127.0.0.1:3001
VITE_APP_ADMIN_API_BASE_URL=http://127.0.0.1:3001
${platformKey ? `PLATFORM_API_KEY=${platformKey}` : '# PLATFORM_API_KEY=set-manually-if-needed'}

# Comunicação externa bloqueada
CONTRACTS_V2_DELIVERY_MODE=disabled
CONTRACTS_V2_RUNTIME_MODE=staging-disabled
CONTRACTS_V2_DATABASE_MODE=postgres-staging-disabled
CONTRACTS_V2_STORAGE_MODE=private-staging-configured
CONTRACTS_V2_PRIVATE_BUCKET=contracts-v2-private-staging
CONTRACTS_V2_RATE_LIMIT_MODE=disabled

VITE_QA_TOOLS_ENABLED=true
VITE_RH_SUPABASE_WRITE=false
`;

  fs.writeFileSync(OUT, body, { mode: 0o600 });
  console.log(JSON.stringify({
    ok: true,
    out: OUT,
    environment: 'STAGING',
    supabaseProject: STAGING_REF,
    usedProduction: false,
    deliveryMode: 'disabled',
    api: 'http://127.0.0.1:3001',
  }));
}

main();
