export const DB_VERSION = 28;

export const defaultDbState = () => ({
  version: DB_VERSION,
  clinicProfile: {
    id: 'clinic-1',
    pessoa: 'JURIDICA',
    nomeMarca: '',
    nomeFantasia: '',
    razaoSocial: '',
    nomeClinica: 'LOVE ODONTO',
    emailPrincipal: '',
    logoUrl: '',
    status: 'ativo',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  clinicDocumentation: {
    clinicId: 'clinic-1',
    cnpj: '',
    ie: '',
    cnes: '',
    nire: '',
    conselhoRegionalNumero: '',
    alvaraPrefeituraNumero: '',
    alvaraAutorizacao: '',
    alvaraValidade: '',
    vigilanciaSanitariaNumero: '',
    vigilanciaSanitariaValidade: '',
    observacoes: '',
  },
  clinicPhones: [],
  clinicAddresses: [],
  clinicBusinessHours: [],
  clinicFiles: [],
  clinicMailServers: [],
  clinicCorrespondence: {
    clinicId: 'clinic-1',
    addressId: '',
    preferEmail: true,
    preferSms: false,
    preferWhatsApp: true,
    notes: '',
  },
  clinicAdditional: {
    clinicId: 'clinic-1',
    notes: '',
  },
  /** Tributação centralizada no cadastro da clínica (consumida pela Precificação) */
  clinicTax: {
    clinicId: 'clinic-1',
    regime: 'simplesNacional',
    uf: 'SP',
    iss: 5,
    baseTributavel: 100,
    simplesAnexo: 'anexo3',
    simplesFaixa: 1,
    aliquotaNominal: 6,
    fatorR: null,
    deducaoPermitida: null,
    tipoCalculo: 'embedded',
  },
  // Precificação: apenas dados operacionais; dados fiscais vêm de clinicTax
  clinicPricing: {
    profile: {
      name: '',
      city: '',
      state: 'SP',
      workAlone: false,
      daysPerWeek: 5,
      hoursPerDay: 8,
      chairs: 1,
    },
    fixedCosts: {
      adminExpenses: [],
      customCosts: [],
    },
    team: {
      employees: [],
      partnerDentists: [],
      partners: [],
    },
    goals: {
      proLabore: 0,
      monthlyRevenue: 0,
      profitMargin: 20,
    },
    equipment: [],
    monthlyRevenue: 0,
    productivity: {
      hoursPerDay: 8,
      daysPerMonth: 22,
      effectiveHours: 6,
      chairs: 1,
    },
    updatedAt: new Date().toISOString(),
    updatedBy: null,
  },
  clinicNfse: {
    clinicId: 'clinic-1',
    provider: '',
    municipalCode: '',
    token: '',
    lastSyncAt: '',
  },
  clinicIntegrations: {
    clinicId: 'clinic-1',
    whatsappApiUrl: '',
    smsProvider: '',
    webhookUrl: '',
  },
  clinicWebPresence: {
    clinicId: 'clinic-1',
    website: '',
    instagram: '',
    facebook: '',
    googleMapsUrl: '',
    whatsappUrl: '',
  },
  clinicLicense: {
    clinicId: 'clinic-1',
    plan: 'standard',
    expiresAt: '',
    seats: 5,
  },
  collaborators: [],
  collaboratorDocuments: [],
  collaboratorEducation: [],
  collaboratorNationality: [],
  collaboratorPhones: [],
  collaboratorAddresses: [],
  collaboratorRelationships: [],
  collaboratorCharacteristics: [],
  collaboratorAdditional: [],
  collaboratorInsurances: [],
  collaboratorAccess: [],
  collaboratorWorkHours: [],
  collaboratorFinance: [],
  users: [
    {
      id: 'user-admin',
      name: 'Administrador',
      role: 'admin',
      active: true,
      has_system_access: true,
    },
  ],
  rooms: [
    {
      id: 'room-1',
      name: 'Consultório 1',
      active: true,
    },
  ],
  patients: [],
  patientDocuments: [],
  patientBirth: [],
  patientEducation: [],
  patientPhones: [],
  patientAddresses: [],
  patientRelationships: [],
  patientInsurances: [],
  patientAccess: [],
  patientActivitySummary: [],
  patientRecords: [],
  appointments: [],
  appointmentBlocks: [],
  transactions: [],
  installmentPlans: [],
  messageTemplates: [],
  messageQueue: [],
  messageLogs: [],
  materials: [],
  stockMovements: [],
  suppliers: [],
  purchases: [],
  automationTasks: [],
  timeEntries: [],
  auditLogs: [],
  patientCharts: [],
  patientCharacteristics: [],
  patientAnamnesisClinical: [],
  patientAnamnesisAtm: [],
  patientOdontograms: [],
  patientOdontogramHistory: [],
  patientFiles: [],
  patientConfidentialFiles: [],
  patientPhotoAlbums: [],
  patientAlbumPhotos: [],
  accessAuditLogs: [],
  patientOdontogramsV2: [],
  clinicalAppointments: [],
  clinicalEvents: [],
  patientJourneyEntries: [],
  priceTables: [],
  priceTableProcedures: [],
  documentRecords: [],
  // CRM Clínico (v16+): estágios padrão para Kanban (evita tela branca em DB novo)
  crmLeads: [],
  crmPipelineStages: [
    { id: 'crm-stage-1', key: 'novo_lead', label: 'Novo Lead', order: 1, color: '#94a3b8' },
    { id: 'crm-stage-2', key: 'contato_realizado', label: 'Contato Realizado', order: 2, color: '#60a5fa' },
    { id: 'crm-stage-3', key: 'avaliacao_agendada', label: 'Avaliação Agendada', order: 3, color: '#a78bfa' },
    { id: 'crm-stage-4', key: 'avaliacao_realizada', label: 'Avaliação Realizada', order: 4, color: '#c084fc' },
    { id: 'crm-stage-5', key: 'orcamento_apresentado', label: 'Orçamento Apresentado', order: 5, color: '#f59e0b' },
    { id: 'crm-stage-6', key: 'em_negociacao', label: 'Em Negociação', order: 6, color: '#fbbf24' },
    { id: 'crm-stage-7', key: 'aprovado', label: 'Aprovado', order: 7, color: '#34d399' },
    { id: 'crm-stage-8', key: 'em_tratamento', label: 'Em Tratamento', order: 8, color: '#22c55e' },
    { id: 'crm-stage-9', key: 'finalizado', label: 'Finalizado', order: 9, color: '#10b981' },
    { id: 'crm-stage-10', key: 'perdido', label: 'Perdido', order: 10, color: '#ef4444' },
  ],
  crmLeadEvents: [],
  crmFollowUps: [],
  crmAutomations: [],
  crmMessageLogs: [],
  crmBudgetLinks: [],
  /** Orçamentos do CRM (crm_budgets) */
  crmBudgets: [],
  /** Tags categorizadas do CRM (crm_tags) */
  crmTags: [],
  /** Vínculo lead–tag (lead_tags) */
  leadTags: [],
  /** Follow-ups estratégicos (Gestão Comercial): retornos, tarefas, orçamentos pendentes */
  followUps: [],
  /** Tarefas/Follow-up do CRM (vinculadas a lead/patient/budget/appointment) */
  crmTasks: [],
  /** Multi-tenant: 1 tenant (clínica) por instalação; MASTER gerencia acessos */
  tenants: [],
  users_profile: [],
  memberships: [],
  invitations: [],
  /** Painel Master: cobrança, planos, assinaturas, faturas */
  plans: [],
  subscriptions: [],
  invoices: [],
  payments: [],
  usage_events: [],
  /** Credenciais de acesso (email + hash) vinculadas ao colaborador */
  userAuth: [],
  /** Convites para ativação de acesso (token hasheado) */
  userInvites: [],
  // version inicial 23 para que a migration 24 (RBAC) rode na primeira carga
  version: 23,
});
