export const AGENDA_CONFIG = {
  time: {
    startHour: 7,
    endHour: 20,
    slotMinutes: 15,
  },
  durations: [15, 30, 45, 60, 90, 120],
  channels: [
    { value: 'whatsapp', label: 'WhatsApp' },
    { value: 'telefone', label: 'Telefone' },
    { value: 'presencial', label: 'Presencial' },
  ],
  status: {
    agendado: {
      label: 'Agendado',
      tone: 'neutral',
      color: '#334155',
      background: '#e2e8f0',
      border: '#94a3b8',
      borderLeft: '#475569',
      badgeVariant: 'neutral',
      colorClass: 'status-gray',
      bgClass: 'status-bg-gray',
      borderClass: 'status-border-gray',
    },
    confirmado: {
      label: 'Confirmado',
      tone: 'success',
      color: '#047857',
      background: '#a7f3d0',
      border: '#34d399',
      borderLeft: '#10b981',
      badgeVariant: 'success',
      colorClass: 'status-green',
      bgClass: 'status-bg-green',
      borderClass: 'status-border-green',
    },
    em_confirmacao: {
      label: 'Em Confirmação',
      tone: 'warning',
      color: '#d97706',
      background: '#fde68a',
      border: '#fbbf24',
      borderLeft: '#f59e0b',
      badgeVariant: 'warning',
      colorClass: 'status-yellow',
      bgClass: 'status-bg-yellow',
      borderClass: 'status-border-yellow',
    },
    cancelado: {
      label: 'Desmarcou',
      tone: 'warning',
      color: '#ea580c',
      background: '#fed7aa',
      border: '#fdba74',
      borderLeft: '#fb923c',
      badgeVariant: 'warning',
      colorClass: 'status-orange',
      bgClass: 'status-bg-orange',
      borderClass: 'status-border-orange',
    },
    faltou: {
      label: 'Falta',
      tone: 'danger',
      color: '#dc2626',
      background: '#fecaca',
      border: '#f87171',
      borderLeft: '#ef4444',
      badgeVariant: 'danger',
      colorClass: 'status-red',
      bgClass: 'status-bg-red',
      borderClass: 'status-border-red',
    },
    reagendar: {
      label: 'Reagendar',
      tone: 'info',
      color: '#7c3aed',
      background: '#e9d5ff',
      border: '#c084fc',
      borderLeft: '#9333ea',
      badgeVariant: 'info',
      colorClass: 'status-purple',
      bgClass: 'status-bg-purple',
      borderClass: 'status-border-purple',
    },
    atendido: {
      label: 'Concluído',
      tone: 'info',
      color: '#1e40af',
      background: '#bfdbfe',
      border: '#60a5fa',
      borderLeft: '#3b82f6',
      badgeVariant: 'info',
      colorClass: 'status-blue',
      bgClass: 'status-bg-blue',
      borderClass: 'status-border-blue',
    },
    chegou: {
      label: 'Chegou',
      tone: 'info',
      color: '#1e40af',
      background: '#dbeafe',
      border: '#60a5fa',
      borderLeft: '#2563eb',
      badgeVariant: 'info',
      colorClass: 'status-blue',
      bgClass: 'status-bg-blue',
      borderClass: 'status-border-blue',
    },
    em_espera: {
      label: 'Em Espera',
      tone: 'warning',
      color: '#d97706',
      background: '#fef3c7',
      border: '#fcd34d',
      borderLeft: '#f59e0b',
      badgeVariant: 'warning',
      colorClass: 'status-yellow',
      bgClass: 'status-bg-yellow',
      borderClass: 'status-border-yellow',
    },
    atrasado: {
      label: 'Atrasado',
      tone: 'warning',
      color: '#ea580c',
      background: '#fed7aa',
      border: '#fdba74',
      borderLeft: '#fb923c',
      badgeVariant: 'warning',
      colorClass: 'status-orange',
      bgClass: 'status-bg-orange',
      borderClass: 'status-border-orange',
    },
    chamado: {
      label: 'Chamado',
      tone: 'info',
      color: '#7c3aed',
      background: '#e9d5ff',
      border: '#c084fc',
      borderLeft: '#9333ea',
      badgeVariant: 'info',
      colorClass: 'status-purple',
      bgClass: 'status-bg-purple',
      borderClass: 'status-border-purple',
    },
    em_atendimento: {
      label: 'Em Atendimento',
      tone: 'info',
      color: '#1e40af',
      background: '#dbeafe',
      border: '#60a5fa',
      borderLeft: '#2563eb',
      badgeVariant: 'info',
      colorClass: 'status-blue',
      bgClass: 'status-bg-blue',
      borderClass: 'status-border-blue',
    },
    finalizado: {
      label: 'Finalizado',
      tone: 'success',
      color: '#047857',
      background: '#d1fae5',
      border: '#34d399',
      borderLeft: '#10b981',
      badgeVariant: 'success',
      colorClass: 'status-green',
      bgClass: 'status-bg-green',
      borderClass: 'status-border-green',
    },
  },
};
