import {
  LayoutDashboard,
  Clock,
  CheckCircle2,
  FileText,
  ScrollText,
  PenLine,
  Settings,
  Layers,
  ListFilter,
} from 'lucide-react';
import { CONTRACTS_V2_SURFACE } from '../domain/contracts/contracts-v2-technical-harness.ts';

export const contractsShellNavItems = [
  { id: 'dashboard', label: 'Dashboard', route: '/gestao/contratos', icon: LayoutDashboard, rolesAllowed: ['admin', 'gerente', 'recepcao'] },
  {
    id: 'fila',
    label: 'Fila',
    route: '/gestao/contratos/fila',
    icon: ListFilter,
    rolesAllowed: ['admin', 'gerente', 'recepcao'],
    surface: CONTRACTS_V2_SURFACE.OPERATIONAL_UI,
  },
  { id: 'pendentes', label: 'Pendentes', route: '/gestao/contratos/pendentes', icon: Clock, rolesAllowed: ['admin', 'gerente', 'recepcao'] },
  { id: 'assinados', label: 'Assinados', route: '/gestao/contratos/assinados', icon: CheckCircle2, rolesAllowed: ['admin', 'gerente', 'recepcao'] },
  { id: 'modelos', label: 'Modelos', route: '/gestao/contratos/modelos', icon: FileText, rolesAllowed: ['admin', 'gerente'] },
  {
    id: 'modelos-v2',
    label: 'Modelos v2',
    route: '/gestao/contratos/modelos-v2',
    icon: Layers,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    /** Flags operacionais NÃO bastam — ver isContractsV2TechnicalHarnessEnabled. */
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contract_templates_v2_enabled',
    ],
  },
  {
    id: 'instancias-v2',
    label: 'Instâncias v2',
    route: '/gestao/contratos/instancias-v2',
    icon: FileText,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contracts_module_v2_enabled',
      'contract_versioning_enabled',
    ],
  },
  { id: 'termos', label: 'Termos', route: '/gestao/contratos/termos', icon: ScrollText, rolesAllowed: ['admin', 'gerente'] },
  { id: 'assinaturas', label: 'Assinaturas', route: '/gestao/contratos/assinaturas', icon: PenLine, rolesAllowed: ['admin', 'gerente', 'recepcao'] },
  {
    id: 'assinaturas-v2',
    label: 'Assinaturas v2',
    route: '/gestao/contratos/assinaturas-v2',
    icon: PenLine,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contracts_module_v2_enabled',
      'contract_versioning_enabled',
      'contract_internal_signature_v2_enabled',
    ],
  },
  {
    id: 'documentos-v2',
    label: 'Documentos v2',
    route: '/gestao/contratos/documentos-v2',
    icon: FileText,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contracts_module_v2_enabled',
      'contract_versioning_enabled',
      'contract_pdf_v2_enabled',
      'contract_storage_v2_enabled',
    ],
  },
  {
    id: 'conclusao-v2',
    label: 'Conclusão v2',
    route: '/gestao/contratos/conclusao-v2',
    icon: CheckCircle2,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contracts_module_v2_enabled',
      'contract_versioning_enabled',
      'contract_internal_signature_v2_enabled',
      'contract_pdf_v2_enabled',
      'contract_storage_v2_enabled',
      'contract_audit_ledger_enabled',
    ],
  },
  {
    id: 'entregas-v2',
    label: 'Entregas v2',
    route: '/gestao/contratos/entregas-v2',
    icon: PenLine,
    rolesAllowed: ['admin', 'master'],
    surface: CONTRACTS_V2_SURFACE.TECHNICAL_HARNESS,
    featureFlagsAll: [
      'contracts_domain_v2_enabled',
      'contracts_module_v2_enabled',
      'contract_versioning_enabled',
      'contract_internal_signature_v2_enabled',
      'contract_pdf_v2_enabled',
      'contract_storage_v2_enabled',
      'contract_audit_ledger_enabled',
      'contract_patient_portal_enabled',
    ],
  },
  { id: 'config', label: 'Configurações', route: '/gestao/contratos/configuracoes', icon: Settings, rolesAllowed: ['admin', 'gerente'] },
];
