/**
 * Phase 9.3A — mapa funcional real (somente o que existe no schema/código).
 * Não inventa tabelas. Fonte: supabase/migrations + bootstrap local + services.
 */
export const PHASE_9_3A_DOMAIN_MAP = [
  {
    domain: 'tenants',
    table: 'public.tenants',
    pk: 'id uuid',
    tenant_id: 'N/A (raiz)',
    relationships: 'referenciada por tabelas app',
    required: 'legal_name, status',
    rls: 'helpers JWT em 002; CREATE no bootstrap 000',
    service: 'tenantProvisionApi / tenantContextService',
    indexedDb: false,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'tenant_users',
    table: 'public.tenant_users',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'tenants; user_id auth; collaborator_uuid→collaborators',
    required: 'tenant_id; email unique por tenant (010)',
    rls: '009/012 app_user_is_tenant_admin',
    service: 'membership / usersApi / provisioning',
    indexedDb: false,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'collaborators',
    table: 'public.collaborators',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'tenants; storage collaborator-photos',
    required: 'apelido, nome_completo, rh_categoria, cargo, tipo_vinculo, setor, status',
    rls: '019',
    service: 'collaboratorService / collaboratorsApi (flags RH_* default off)',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'patients',
    table: 'public.patients (+ phones/documents/records)',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'legacy_id patient-*; refs text opacas em appointments/crm_leads/financial_*',
    required: 'legacy_id, full_name',
    rls: '025 (SELECT JWT + mutate admin)',
    service: 'patientService → IndexedDB (repository scaffold não wired)',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: true,
    layer: 'sql_inspect_foundation',
    note: 'Phase 9.4A Wave 1 — DDL+RLS; IndexedDB permanece SSOT app até cutover',
  },
  {
    domain: 'crm_pipeline_stages',
    table: 'public.crm_pipeline_stages',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'tenants; key lógico referenciado por crm_leads.stage_key',
    required: 'legacy_id, key, label',
    rls: '023',
    service: 'crmService / crmApiWrite (flags CRM_* default off)',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'crm_leads',
    table: 'public.crm_leads',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'tenants; patient_id text opaco',
    required: 'legacy_id, stage_key',
    rls: '023',
    service: 'crmService / crmApiWrite',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'appointments',
    table: 'public.appointments',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'patient_id/lead_id/professional_id text opacos',
    required: 'legacy_id, date, start_time, end_time, status',
    rls: '023',
    service: 'appointmentService / appointmentsApiWrite',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'patient_journey',
    table: null,
    pk: null,
    tenant_id: null,
    relationships: null,
    required: null,
    rls: null,
    service: 'journeyEntryService / patientFlowService → IDB',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: false,
    layer: 'out_of_scope_idb',
  },
  {
    domain: 'budgets_quotes',
    table: null,
    pk: null,
    tenant_id: null,
    relationships: 'budget_id text em financial_*/generated_contracts',
    required: null,
    rls: null,
    service: 'crmBudgetService / clinicalBudget* → IDB; budgetsService órfão',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: false,
    layer: 'out_of_scope_idb',
    note: 'E2E usa quote_id/budget_id opacos determinísticos',
  },
  {
    domain: 'generated_contracts',
    table: 'public.generated_contracts',
    pk: 'id text',
    tenant_id: 'uuid NOT NULL',
    relationships: 'patient_id/quote_id text; quote_source crm_budget|clinical_budget',
    required: 'patient_id, quote_id, quote_source, status',
    rls: '006 app_user_can_access_tenant',
    service: 'contractsGeneratedApi / contractSaasSyncService',
    indexedDb: true,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'financial_receivables',
    table: 'public.financial_accounts_receivable',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'patient/contract/budget text; sem tabela payments SQL',
    required: 'legacy_id; amounts ≥ 0',
    rls: '023',
    service: 'receivablesService / financialApiWrite',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'financial_financings',
    table: 'public.financial_financings',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL',
    relationships: 'cabeçalho; parcelas só IDB',
    required: 'legacy_id',
    rls: '023',
    service: 'financingsService / financialApiWrite',
    indexedDb: true,
    supabaseWrite: 'condicional (flag)',
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'payments_installments',
    table: null,
    pk: null,
    tenant_id: null,
    relationships: null,
    required: null,
    rls: null,
    service: 'receivablePayments IDB',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: false,
    layer: 'out_of_scope_idb',
    note: 'Simulado via paid_amount no header receivable',
  },
  {
    domain: 'clinical_records_odontogram',
    table: null,
    pk: null,
    tenant_id: null,
    relationships: null,
    required: null,
    rls: null,
    service: 'clinicalService / patientOdontogram* → IDB',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: false,
    layer: 'out_of_scope_idb',
  },
  {
    domain: 'clinic_profiles',
    table: 'public.clinic_profiles',
    pk: 'id uuid',
    tenant_id: 'uuid NOT NULL UNIQUE',
    relationships: 'tenants',
    required: 'name, status',
    rls: '014',
    service: 'clinicProfileApi / assetsLogoApi',
    indexedDb: true,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'contract_audit',
    table: 'public.contract_audit_logs',
    pk: 'id text',
    tenant_id: 'uuid NOT NULL',
    relationships: 'contract_id text',
    required: 'action',
    rls: '006',
    service: 'contractsGeneratedApi',
    indexedDb: false,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_fixture',
  },
  {
    domain: 'operational_audit',
    table: null,
    pk: null,
    tenant_id: null,
    relationships: null,
    required: null,
    rls: null,
    service: 'accessAuditService IDB / eventAuditProjectionStore in-memory',
    indexedDb: true,
    supabaseWrite: false,
    inScopeSqlE2e: false,
    layer: 'out_of_scope_idb',
  },
  {
    domain: 'storage',
    table: 'storage.buckets / storage.objects',
    pk: 'bucket id text',
    tenant_id: 'path foldername[1]',
    relationships: 'clinic-logos, collaborator-photos, clinical-guides',
    required: 'path canônico por bucket',
    rls: '013/024/007',
    service: 'assetsLogoApi / assetsAvatarApi',
    indexedDb: false,
    supabaseWrite: true,
    inScopeSqlE2e: true,
    layer: 'sql_inspect',
    note: 'E2E valida presença de buckets/policies; upload binário fora desta phase',
  },
];

export const PHASE_9_3A_TEST_LAYER = {
  preference: [
    'SQL fixture para bootstrap multi-tenant e fluxo SSOT local',
    'SET LOCAL ROLE authenticated + JWT claims para isolamento (mesmos helpers RLS da app)',
    'Não duplicar Admin API/services com flags default-off nesta phase',
    'Marcar patients/budgets/journey/payments/odontogram/audit operacional como OUT_OF_SCOPE_IDB',
  ],
  executionModes: {
    sql_fixture: 'bootstrap + escrita funcional nas tabelas SSOT',
    jwt_rls: 'asserts cross-tenant com role authenticated',
    out_of_scope_idb: 'documentado, não simulado com segunda implementação',
  },
};
