insert into public.permission_catalog (id, module_group_key, module_group_label, module_key, module_label, action_key, description, sort_order) values
'perm-comercial_captacao_leads-view', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'view', 'Gestão Comercial • Captação de Leads • Ver', 1,
  ('perm-comercial_captacao_leads-create', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'create', 'Gestão Comercial • Captação de Leads • Criar', 2,
  ('perm-comercial_captacao_leads-edit', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'edit', 'Gestão Comercial • Captação de Leads • Editar', 3,
  ('perm-comercial_captacao_leads-delete', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'delete', 'Gestão Comercial • Captação de Leads • Excluir', 4,
  ('perm-comercial_captacao_leads-export', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'export', 'Gestão Comercial • Captação de Leads • Exportar', 5,
  ('perm-pipeline_crm-view', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'view', 'Gestão Comercial • Pipeline de Atendimento • Ver', 6,
  ('perm-pipeline_crm-create', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'create', 'Gestão Comercial • Pipeline de Atendimento • Criar', 7,
  ('perm-pipeline_crm-edit', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'edit', 'Gestão Comercial • Pipeline de Atendimento • Editar', 8,
  ('perm-pipeline_crm-move_stage', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'move_stage', 'Gestão Comercial • Pipeline de Atendimento • Mover', 9,
  ('perm-pipeline_crm-delete', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'delete', 'Gestão Comercial • Pipeline de Atendimento • Excluir', 10,
  ('perm-comercial_leads-view', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'view', 'Gestão Comercial • Leads • Ver', 11,
  ('perm-comercial_leads-create', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'create', 'Gestão Comercial • Leads • Criar', 12,
  ('perm-comercial_leads-edit', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'edit', 'Gestão Comercial • Leads • Editar', 13,
  ('perm-comercial_leads-delete', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'delete', 'Gestão Comercial • Leads • Excluir', 14,
  ('perm-comercial_leads-export', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'export', 'Gestão Comercial • Leads • Exportar', 15,
  ('perm-comercial_historico_chats-view', 'comercial', 'Gestão Comercial', 'comercial_historico_chats', 'Histórico de Chats', 'view', 'Gestão Comercial • Histórico de Chats • Ver', 16,
  ('perm-comercial_historico_chats-export', 'comercial', 'Gestão Comercial', 'comercial_historico_chats', 'Histórico de Chats', 'export', 'Gestão Comercial • Histórico de Chats • Exportar', 17,
  ('perm-comercial_mensagens_automaticas-view', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'view', 'Gestão Comercial • Mensagens Automáticas • Ver', 18,
  ('perm-comercial_mensagens_automaticas-create', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'create', 'Gestão Comercial • Mensagens Automáticas • Criar', 19,
  ('perm-comercial_mensagens_automaticas-edit', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'edit', 'Gestão Comercial • Mensagens Automáticas • Editar', 20,
  ('perm-comercial_campanhas_broadcast-view', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'view', 'Gestão Comercial • Campanhas/Broadcast • Ver', 21,
  ('perm-comercial_campanhas_broadcast-create', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'create', 'Gestão Comercial • Campanhas/Broadcast • Criar', 22,
  ('perm-comercial_campanhas_broadcast-send', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'send', 'Gestão Comercial • Campanhas/Broadcast • Enviar', 23,
  ('perm-comercial_campanhas_broadcast-cancel', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'cancel', 'Gestão Comercial • Campanhas/Broadcast • Cancelar', 24,
  ('perm-comercial_relatorios-view', 'comercial', 'Gestão Comercial', 'comercial_relatorios', 'Relatórios Comerciais', 'view', 'Gestão Comercial • Relatórios Comerciais • Ver', 25,
  ('perm-comercial_relatorios-export', 'comercial', 'Gestão Comercial', 'comercial_relatorios', 'Relatórios Comerciais', 'export', 'Gestão Comercial • Relatórios Comerciais • Exportar', 26,
  ('perm-patients-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'view', 'Atendimento / Prontuário • Pacientes • Ver', 27,
  ('perm-patients-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'create', 'Atendimento / Prontuário • Pacientes • Criar', 28,
  ('perm-patients-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'edit', 'Atendimento / Prontuário • Pacientes • Editar', 29,
  ('perm-patients-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'delete', 'Atendimento / Prontuário • Pacientes • Excluir', 30,
  ('perm-patients-export', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'export', 'Atendimento / Prontuário • Pacientes • Exportar', 31,
  ('perm-prontuario_atendimento-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'view', 'Atendimento / Prontuário • Prontuário Clínico • Ver', 32,
  ('perm-prontuario_atendimento-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'create', 'Atendimento / Prontuário • Prontuário Clínico • Criar', 33,
  ('perm-prontuario_atendimento-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'edit', 'Atendimento / Prontuário • Prontuário Clínico • Editar', 34,
  ('perm-prontuario_atendimento-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'delete', 'Atendimento / Prontuário • Prontuário Clínico • Excluir', 35,
  ('perm-prontuario_evolucao_clinica-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'view', 'Atendimento / Prontuário • Evolução Clínica • Ver', 36,
  ('perm-prontuario_evolucao_clinica-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'create', 'Atendimento / Prontuário • Evolução Clínica • Criar', 37,
  ('perm-prontuario_evolucao_clinica-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'edit', 'Atendimento / Prontuário • Evolução Clínica • Editar', 38,
  ('perm-prontuario_evolucao_clinica-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'delete', 'Atendimento / Prontuário • Evolução Clínica • Excluir', 39,
  ('perm-prontuario_odontograma-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'view', 'Atendimento / Prontuário • Odontograma • Ver', 40,
  ('perm-prontuario_odontograma-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'create', 'Atendimento / Prontuário • Odontograma • Criar', 41,
  ('perm-prontuario_odontograma-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'edit', 'Atendimento / Prontuário • Odontograma • Editar', 42,
  ('perm-prontuario_planejamento-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'view', 'Atendimento / Prontuário • Planejamento • Ver', 43,
  ('perm-prontuario_planejamento-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'create', 'Atendimento / Prontuário • Planejamento • Criar', 44,
  ('perm-prontuario_planejamento-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'edit', 'Atendimento / Prontuário • Planejamento • Editar', 45,
  ('perm-prontuario_planejamento-approve', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'approve', 'Atendimento / Prontuário • Planejamento • Aprovar', 46,
  ('perm-prontuario_procedimentos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'view', 'Atendimento / Prontuário • Procedimentos a Realizar • Ver', 47,
  ('perm-prontuario_procedimentos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'create', 'Atendimento / Prontuário • Procedimentos a Realizar • Criar', 48,
  ('perm-prontuario_procedimentos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'edit', 'Atendimento / Prontuário • Procedimentos a Realizar • Editar', 49,
  ('perm-prontuario_procedimentos-conclude', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'conclude', 'Atendimento / Prontuário • Procedimentos a Realizar • Concluir', 50)
on conflict (id) do update set module_group_key=excluded.module_group_key, module_group_label=excluded.module_group_label, module_key=excluded.module_key, module_label=excluded.module_label, action_key=excluded.action_key, description=excluded.description, sort_order=excluded.sort_order, updated_at=now();