insert into public.permission_catalog (id, module_group_key, module_group_label, module_key, module_label, action_key, description, sort_order) values
('perm-admin_base_precos_procedimentos-edit', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'edit', 'Administrativo • Base de Preços e Procedimentos • Editar', 101,
  ('perm-admin_base_precos_procedimentos-delete', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'delete', 'Administrativo • Base de Preços e Procedimentos • Excluir', 102,
  ('perm-admin_base_precos_procedimentos-import', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'import', 'Administrativo • Base de Preços e Procedimentos • Importar', 103,
  ('perm-admin_base_precos_procedimentos-export', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'export', 'Administrativo • Base de Preços e Procedimentos • Exportar', 104,
  ('perm-admin_contratos-view', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'view', 'Administrativo • Contratos e Consentimentos • Ver', 105,
  ('perm-admin_contratos-create', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'create', 'Administrativo • Contratos e Consentimentos • Criar', 106,
  ('perm-admin_contratos-edit', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'edit', 'Administrativo • Contratos e Consentimentos • Editar', 107,
  ('perm-admin_contratos-delete', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'delete', 'Administrativo • Contratos e Consentimentos • Excluir', 108,
  ('perm-admin_contratos-update_template', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'update_template', 'Administrativo • Contratos e Consentimentos • Editar modelo', 109,
  ('perm-admin_contratos-generate', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'generate', 'Administrativo • Contratos e Consentimentos • Gerar contrato', 110,
  ('perm-admin_contratos-print', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'print', 'Administrativo • Contratos e Consentimentos • Imprimir', 111,
  ('perm-admin_contratos-export_pdf', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'export_pdf', 'Administrativo • Contratos e Consentimentos • Exportar PDF', 112,
  ('perm-admin_contratos-cancel', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'cancel', 'Administrativo • Contratos e Consentimentos • Cancelar', 113,
  ('perm-admin_contratos-view_audit', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'view_audit', 'Administrativo • Contratos e Consentimentos • Ver auditoria', 114,
  ('perm-admin_contratos-edit_system_clause', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'edit_system_clause', 'Administrativo • Contratos e Consentimentos • Editar cláusula padrão', 115,
  ('perm-admin_consentimentos-view', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'view', 'Administrativo • Consentimentos • Ver', 116,
  ('perm-admin_consentimentos-create', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'create', 'Administrativo • Consentimentos • Criar', 117,
  ('perm-admin_consentimentos-edit', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'edit', 'Administrativo • Consentimentos • Editar', 118,
  ('perm-admin_consentimentos-delete', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'delete', 'Administrativo • Consentimentos • Excluir', 119,
  ('perm-configuracoes-view', 'administrativo', 'Administrativo', 'configuracoes', 'Configurações (Geral)', 'view', 'Administrativo • Configurações (Geral) • Ver', 120,
  ('perm-configuracoes-edit', 'administrativo', 'Administrativo', 'configuracoes', 'Configurações (Geral)', 'edit', 'Administrativo • Configurações (Geral) • Editar', 121,
  ('perm-financeiro_contas_receber-view', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'view', 'Financeiro • Contas a Receber • Ver', 122,
  ('perm-financeiro_contas_receber-create', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'create', 'Financeiro • Contas a Receber • Criar', 123,
  ('perm-financeiro_contas_receber-edit', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'edit', 'Financeiro • Contas a Receber • Editar', 124,
  ('perm-financeiro_contas_receber-download', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'download', 'Financeiro • Contas a Receber • Baixar', 125,
  ('perm-financeiro_contas_receber-delete', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'delete', 'Financeiro • Contas a Receber • Excluir', 126,
  ('perm-financeiro_contas_receber-export', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'export', 'Financeiro • Contas a Receber • Exportar', 127,
  ('perm-financeiro_contas_pagar-view', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'view', 'Financeiro • Contas a Pagar • Ver', 128,
  ('perm-financeiro_contas_pagar-create', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'create', 'Financeiro • Contas a Pagar • Criar', 129,
  ('perm-financeiro_contas_pagar-edit', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'edit', 'Financeiro • Contas a Pagar • Editar', 130,
  ('perm-financeiro_contas_pagar-download', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'download', 'Financeiro • Contas a Pagar • Baixar', 131,
  ('perm-financeiro_contas_pagar-delete', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'delete', 'Financeiro • Contas a Pagar • Excluir', 132,
  ('perm-financeiro_contas_pagar-export', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'export', 'Financeiro • Contas a Pagar • Exportar', 133,
  ('perm-financeiro_caixa-view', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'view', 'Financeiro • Caixa • Ver', 134,
  ('perm-financeiro_caixa-open', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'open', 'Financeiro • Caixa • Abrir', 135,
  ('perm-financeiro_caixa-close', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'close', 'Financeiro • Caixa • Fechar', 136,
  ('perm-financeiro_caixa-launch', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'launch', 'Financeiro • Caixa • Lançar', 137,
  ('perm-financeiro_caixa-reverse', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'reverse', 'Financeiro • Caixa • Estornar', 138,
  ('perm-financeiro_boletos-view', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'view', 'Financeiro • Boletos/Cobranças • Ver', 139,
  ('perm-financeiro_boletos-create', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'create', 'Financeiro • Boletos/Cobranças • Criar', 140,
  ('perm-financeiro_boletos-issue', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'issue', 'Financeiro • Boletos/Cobranças • Emitir', 141,
  ('perm-financeiro_boletos-cancel', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'cancel', 'Financeiro • Boletos/Cobranças • Cancelar', 142,
  ('perm-financeiro_boletos-resend', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'resend', 'Financeiro • Boletos/Cobranças • Reenviar', 143,
  ('perm-financeiro_financiamentos-view', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'view', 'Financeiro • Financiamentos • Ver', 144,
  ('perm-financeiro_financiamentos-create', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'create', 'Financeiro • Financiamentos • Criar', 145,
  ('perm-financeiro_financiamentos-edit', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'edit', 'Financeiro • Financiamentos • Editar', 146,
  ('perm-financeiro_financiamentos-approve', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'approve', 'Financeiro • Financiamentos • Aprovar', 147,
  ('perm-financeiro_financiamentos-cancel', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'cancel', 'Financeiro • Financiamentos • Cancelar', 148,
  ('perm-financeiro_comissoes-view', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'view', 'Financeiro • Comissões • Ver', 149,
  ('perm-financeiro_comissoes-create', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'create', 'Financeiro • Comissões • Criar', 150)
on conflict (id) do update set module_group_key=excluded.module_group_key, module_group_label=excluded.module_group_label, module_key=excluded.module_key, module_label=excluded.module_label, action_key=excluded.action_key, description=excluded.description, sort_order=excluded.sort_order, updated_at=now();