insert into public.permission_catalog (id, module_group_key, module_group_label, module_key, module_label, action_key, description, sort_order) values
('perm-financeiro_comissoes-edit', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'edit', 'Financeiro • Comissões • Editar', 151,
  ('perm-financeiro_comissoes-approve', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'approve', 'Financeiro • Comissões • Aprovar', 152,
  ('perm-financeiro_comissoes-export', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'export', 'Financeiro • Comissões • Exportar', 153,
  ('perm-financeiro_dre-view', 'financeiro', 'Financeiro', 'financeiro_dre', 'DRE / Central de Análise', 'view', 'Financeiro • DRE / Central de Análise • Ver', 154,
  ('perm-financeiro_dre-export', 'financeiro', 'Financeiro', 'financeiro_dre', 'DRE / Central de Análise', 'export', 'Financeiro • DRE / Central de Análise • Exportar', 155,
  ('perm-financeiro_relatorios-view', 'financeiro', 'Financeiro', 'financeiro_relatorios', 'Relatórios Financeiros', 'view', 'Financeiro • Relatórios Financeiros • Ver', 156,
  ('perm-financeiro_relatorios-export', 'financeiro', 'Financeiro', 'financeiro_relatorios', 'Relatórios Financeiros', 'export', 'Financeiro • Relatórios Financeiros • Exportar', 157,
  ('perm-dashboard-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'dashboard', 'Dashboard Geral', 'view', 'Dashboard / Relatórios • Dashboard Geral • Ver', 158,
  ('perm-dashboard_indicadores-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'dashboard_indicadores', 'Indicadores Principais', 'view', 'Dashboard / Relatórios • Indicadores Principais • Ver', 159,
  ('perm-relatorios_gerenciais-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_gerenciais', 'Relatórios Gerenciais', 'view', 'Dashboard / Relatórios • Relatórios Gerenciais • Ver', 160,
  ('perm-relatorios_gerenciais-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_gerenciais', 'Relatórios Gerenciais', 'export', 'Dashboard / Relatórios • Relatórios Gerenciais • Exportar', 161,
  ('perm-relatorios_atendimento-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_atendimento', 'Relatórios de Atendimento', 'view', 'Dashboard / Relatórios • Relatórios de Atendimento • Ver', 162,
  ('perm-relatorios_atendimento-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_atendimento', 'Relatórios de Atendimento', 'export', 'Dashboard / Relatórios • Relatórios de Atendimento • Exportar', 163,
  ('perm-relatorios_comerciais-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_comerciais', 'Relatórios Comerciais', 'view', 'Dashboard / Relatórios • Relatórios Comerciais • Ver', 164,
  ('perm-relatorios_comerciais-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_comerciais', 'Relatórios Comerciais', 'export', 'Dashboard / Relatórios • Relatórios Comerciais • Exportar', 165,
  ('perm-relatorios-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios', 'Relatórios Financeiros', 'view', 'Dashboard / Relatórios • Relatórios Financeiros • Ver', 166,
  ('perm-relatorios-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios', 'Relatórios Financeiros', 'export', 'Dashboard / Relatórios • Relatórios Financeiros • Exportar', 167,
  ('perm-sistema_integracoes-view', 'config_sistema', 'Configurações / Sistema', 'sistema_integracoes', 'Integrações', 'view', 'Configurações / Sistema • Integrações • Ver', 168,
  ('perm-sistema_integracoes-configure', 'config_sistema', 'Configurações / Sistema', 'sistema_integracoes', 'Integrações', 'configure', 'Configurações / Sistema • Integrações • Configurar', 169,
  ('perm-sistema_whatsapp-view', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'view', 'Configurações / Sistema • WhatsApp • Ver', 170,
  ('perm-sistema_whatsapp-configure', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'configure', 'Configurações / Sistema • WhatsApp • Configurar', 171,
  ('perm-sistema_whatsapp-connect', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'connect', 'Configurações / Sistema • WhatsApp • Conectar', 172,
  ('perm-sistema_whatsapp-disconnect', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'disconnect', 'Configurações / Sistema • WhatsApp • Desconectar', 173,
  ('perm-sistema_suporte-view', 'config_sistema', 'Configurações / Sistema', 'sistema_suporte', 'Suporte', 'view', 'Configurações / Sistema • Suporte • Ver', 174,
  ('perm-sistema_suporte-create_ticket', 'config_sistema', 'Configurações / Sistema', 'sistema_suporte', 'Suporte', 'create_ticket', 'Configurações / Sistema • Suporte • Criar chamado', 175,
  ('perm-sistema_logs_auditoria-view', 'config_sistema', 'Configurações / Sistema', 'sistema_logs_auditoria', 'Logs/Auditoria', 'view', 'Configurações / Sistema • Logs/Auditoria • Ver', 176,
  ('perm-sistema_logs_auditoria-export', 'config_sistema', 'Configurações / Sistema', 'sistema_logs_auditoria', 'Logs/Auditoria', 'export', 'Configurações / Sistema • Logs/Auditoria • Exportar', 177,
  ('perm-sistema_preferencias-view', 'config_sistema', 'Configurações / Sistema', 'sistema_preferencias', 'Preferências do Sistema', 'view', 'Configurações / Sistema • Preferências do Sistema • Ver', 178,
  ('perm-sistema_preferencias-edit', 'config_sistema', 'Configurações / Sistema', 'sistema_preferencias', 'Preferências do Sistema', 'edit', 'Configurações / Sistema • Preferências do Sistema • Editar', 179,
  ('perm-estoque-view', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'view', 'Configurações / Sistema • Estoque / Materiais • Ver', 180,
  ('perm-estoque-create', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'create', 'Configurações / Sistema • Estoque / Materiais • Criar', 181,
  ('perm-estoque-edit', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'edit', 'Configurações / Sistema • Estoque / Materiais • Editar', 182,
  ('perm-estoque-delete', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'delete', 'Configurações / Sistema • Estoque / Materiais • Excluir', 183,
  ('perm-estoque-export', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'export', 'Configurações / Sistema • Estoque / Materiais • Exportar', 184)
on conflict (id) do update set module_group_key=excluded.module_group_key, module_group_label=excluded.module_group_label, module_key=excluded.module_key, module_label=excluded.module_label, action_key=excluded.action_key, description=excluded.description, sort_order=excluded.sort_order, updated_at=now();