insert into public.permission_catalog (  id, module_group_key, module_group_label, module_key, module_label, action_key, description, sort_order
)
values
  ('perm-comercial_captacao_leads-view', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'view', 'Gestão Comercial • Captação de Leads • Ver', 1),
  ('perm-comercial_captacao_leads-create', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'create', 'Gestão Comercial • Captação de Leads • Criar', 2),
  ('perm-comercial_captacao_leads-edit', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'edit', 'Gestão Comercial • Captação de Leads • Editar', 3),
  ('perm-comercial_captacao_leads-delete', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'delete', 'Gestão Comercial • Captação de Leads • Excluir', 4),
  ('perm-comercial_captacao_leads-export', 'comercial', 'Gestão Comercial', 'comercial_captacao_leads', 'Captação de Leads', 'export', 'Gestão Comercial • Captação de Leads • Exportar', 5),
  ('perm-pipeline_crm-view', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'view', 'Gestão Comercial • Pipeline de Atendimento • Ver', 6),
  ('perm-pipeline_crm-create', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'create', 'Gestão Comercial • Pipeline de Atendimento • Criar', 7),
  ('perm-pipeline_crm-edit', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'edit', 'Gestão Comercial • Pipeline de Atendimento • Editar', 8),
  ('perm-pipeline_crm-move_stage', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'move_stage', 'Gestão Comercial • Pipeline de Atendimento • Mover', 9),
  ('perm-pipeline_crm-delete', 'comercial', 'Gestão Comercial', 'pipeline_crm', 'Pipeline de Atendimento', 'delete', 'Gestão Comercial • Pipeline de Atendimento • Excluir', 10),
  ('perm-comercial_leads-view', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'view', 'Gestão Comercial • Leads • Ver', 11),
  ('perm-comercial_leads-create', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'create', 'Gestão Comercial • Leads • Criar', 12),
  ('perm-comercial_leads-edit', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'edit', 'Gestão Comercial • Leads • Editar', 13),
  ('perm-comercial_leads-delete', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'delete', 'Gestão Comercial • Leads • Excluir', 14),
  ('perm-comercial_leads-export', 'comercial', 'Gestão Comercial', 'comercial_leads', 'Leads', 'export', 'Gestão Comercial • Leads • Exportar', 15),
  ('perm-comercial_historico_chats-view', 'comercial', 'Gestão Comercial', 'comercial_historico_chats', 'Histórico de Chats', 'view', 'Gestão Comercial • Histórico de Chats • Ver', 16),
  ('perm-comercial_historico_chats-export', 'comercial', 'Gestão Comercial', 'comercial_historico_chats', 'Histórico de Chats', 'export', 'Gestão Comercial • Histórico de Chats • Exportar', 17),
  ('perm-comercial_mensagens_automaticas-view', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'view', 'Gestão Comercial • Mensagens Automáticas • Ver', 18),
  ('perm-comercial_mensagens_automaticas-create', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'create', 'Gestão Comercial • Mensagens Automáticas • Criar', 19),
  ('perm-comercial_mensagens_automaticas-edit', 'comercial', 'Gestão Comercial', 'comercial_mensagens_automaticas', 'Mensagens Automáticas', 'edit', 'Gestão Comercial • Mensagens Automáticas • Editar', 20),
  ('perm-comercial_campanhas_broadcast-view', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'view', 'Gestão Comercial • Campanhas/Broadcast • Ver', 21),
  ('perm-comercial_campanhas_broadcast-create', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'create', 'Gestão Comercial • Campanhas/Broadcast • Criar', 22),
  ('perm-comercial_campanhas_broadcast-send', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'send', 'Gestão Comercial • Campanhas/Broadcast • Enviar', 23),
  ('perm-comercial_campanhas_broadcast-cancel', 'comercial', 'Gestão Comercial', 'comercial_campanhas_broadcast', 'Campanhas/Broadcast', 'cancel', 'Gestão Comercial • Campanhas/Broadcast • Cancelar', 24),
  ('perm-comercial_relatorios-view', 'comercial', 'Gestão Comercial', 'comercial_relatorios', 'Relatórios Comerciais', 'view', 'Gestão Comercial • Relatórios Comerciais • Ver', 25),
  ('perm-comercial_relatorios-export', 'comercial', 'Gestão Comercial', 'comercial_relatorios', 'Relatórios Comerciais', 'export', 'Gestão Comercial • Relatórios Comerciais • Exportar', 26),
  ('perm-patients-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'view', 'Atendimento / Prontuário • Pacientes • Ver', 27),
  ('perm-patients-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'create', 'Atendimento / Prontuário • Pacientes • Criar', 28),
  ('perm-patients-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'edit', 'Atendimento / Prontuário • Pacientes • Editar', 29),
  ('perm-patients-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'delete', 'Atendimento / Prontuário • Pacientes • Excluir', 30),
  ('perm-patients-export', 'atendimento_prontuario', 'Atendimento / Prontuário', 'patients', 'Pacientes', 'export', 'Atendimento / Prontuário • Pacientes • Exportar', 31),
  ('perm-prontuario_atendimento-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'view', 'Atendimento / Prontuário • Prontuário Clínico • Ver', 32),
  ('perm-prontuario_atendimento-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'create', 'Atendimento / Prontuário • Prontuário Clínico • Criar', 33),
  ('perm-prontuario_atendimento-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'edit', 'Atendimento / Prontuário • Prontuário Clínico • Editar', 34),
  ('perm-prontuario_atendimento-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_atendimento', 'Prontuário Clínico', 'delete', 'Atendimento / Prontuário • Prontuário Clínico • Excluir', 35),
  ('perm-prontuario_evolucao_clinica-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'view', 'Atendimento / Prontuário • Evolução Clínica • Ver', 36),
  ('perm-prontuario_evolucao_clinica-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'create', 'Atendimento / Prontuário • Evolução Clínica • Criar', 37),
  ('perm-prontuario_evolucao_clinica-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'edit', 'Atendimento / Prontuário • Evolução Clínica • Editar', 38),
  ('perm-prontuario_evolucao_clinica-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_evolucao_clinica', 'Evolução Clínica', 'delete', 'Atendimento / Prontuário • Evolução Clínica • Excluir', 39),
  ('perm-prontuario_odontograma-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'view', 'Atendimento / Prontuário • Odontograma • Ver', 40),
  ('perm-prontuario_odontograma-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'create', 'Atendimento / Prontuário • Odontograma • Criar', 41),
  ('perm-prontuario_odontograma-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_odontograma', 'Odontograma', 'edit', 'Atendimento / Prontuário • Odontograma • Editar', 42),
  ('perm-prontuario_planejamento-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'view', 'Atendimento / Prontuário • Planejamento • Ver', 43),
  ('perm-prontuario_planejamento-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'create', 'Atendimento / Prontuário • Planejamento • Criar', 44),
  ('perm-prontuario_planejamento-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'edit', 'Atendimento / Prontuário • Planejamento • Editar', 45),
  ('perm-prontuario_planejamento-approve', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_planejamento', 'Planejamento', 'approve', 'Atendimento / Prontuário • Planejamento • Aprovar', 46),
  ('perm-prontuario_procedimentos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'view', 'Atendimento / Prontuário • Procedimentos a Realizar • Ver', 47),
  ('perm-prontuario_procedimentos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'create', 'Atendimento / Prontuário • Procedimentos a Realizar • Criar', 48),
  ('perm-prontuario_procedimentos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'edit', 'Atendimento / Prontuário • Procedimentos a Realizar • Editar', 49),
  ('perm-prontuario_procedimentos-conclude', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_procedimentos', 'Procedimentos a Realizar', 'conclude', 'Atendimento / Prontuário • Procedimentos a Realizar • Concluir', 50),
  ('perm-prontuario_orcamentos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_orcamentos', 'Orçamentos', 'view', 'Atendimento / Prontuário • Orçamentos • Ver', 51),
  ('perm-prontuario_orcamentos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_orcamentos', 'Orçamentos', 'create', 'Atendimento / Prontuário • Orçamentos • Criar', 52),
  ('perm-prontuario_orcamentos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_orcamentos', 'Orçamentos', 'edit', 'Atendimento / Prontuário • Orçamentos • Editar', 53),
  ('perm-prontuario_orcamentos-approve', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_orcamentos', 'Orçamentos', 'approve', 'Atendimento / Prontuário • Orçamentos • Aprovar', 54),
  ('perm-prontuario_orcamentos-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_orcamentos', 'Orçamentos', 'delete', 'Atendimento / Prontuário • Orçamentos • Excluir', 55),
  ('perm-prontuario_guia_clinico-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_guia_clinico', 'Guia Clínico do Dentista', 'view', 'Atendimento / Prontuário • Guia Clínico do Dentista • Ver', 56),
  ('perm-prontuario_guia_clinico-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_guia_clinico', 'Guia Clínico do Dentista', 'create', 'Atendimento / Prontuário • Guia Clínico do Dentista • Criar', 57),
  ('perm-prontuario_guia_clinico-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_guia_clinico', 'Guia Clínico do Dentista', 'edit', 'Atendimento / Prontuário • Guia Clínico do Dentista • Editar', 58),
  ('perm-prontuario_guia_clinico-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_guia_clinico', 'Guia Clínico do Dentista', 'delete', 'Atendimento / Prontuário • Guia Clínico do Dentista • Excluir', 59),
  ('perm-prontuario_contratos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'view', 'Atendimento / Prontuário • Contratos • Ver', 60),
  ('perm-prontuario_contratos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'create', 'Atendimento / Prontuário • Contratos • Criar', 61),
  ('perm-prontuario_contratos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'edit', 'Atendimento / Prontuário • Contratos • Editar', 62),
  ('perm-prontuario_contratos-send', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'send', 'Atendimento / Prontuário • Contratos • Enviar', 63),
  ('perm-prontuario_contratos-sign', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'sign', 'Atendimento / Prontuário • Contratos • Assinar', 64),
  ('perm-prontuario_contratos-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_contratos', 'Contratos', 'delete', 'Atendimento / Prontuário • Contratos • Excluir', 65),
  ('perm-prontuario_consentimentos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_consentimentos', 'Consentimentos', 'view', 'Atendimento / Prontuário • Consentimentos • Ver', 66),
  ('perm-prontuario_consentimentos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_consentimentos', 'Consentimentos', 'create', 'Atendimento / Prontuário • Consentimentos • Criar', 67),
  ('perm-prontuario_consentimentos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_consentimentos', 'Consentimentos', 'edit', 'Atendimento / Prontuário • Consentimentos • Editar', 68),
  ('perm-prontuario_consentimentos-send', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_consentimentos', 'Consentimentos', 'send', 'Atendimento / Prontuário • Consentimentos • Enviar', 69),
  ('perm-prontuario_documentos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_documentos', 'Documentos do Paciente', 'view', 'Atendimento / Prontuário • Documentos do Paciente • Ver', 70),
  ('perm-prontuario_documentos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_documentos', 'Documentos do Paciente', 'create', 'Atendimento / Prontuário • Documentos do Paciente • Criar', 71),
  ('perm-prontuario_documentos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_documentos', 'Documentos do Paciente', 'edit', 'Atendimento / Prontuário • Documentos do Paciente • Editar', 72),
  ('perm-prontuario_documentos-delete', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_documentos', 'Documentos do Paciente', 'delete', 'Atendimento / Prontuário • Documentos do Paciente • Excluir', 73),
  ('perm-prontuario_documentos-export', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_documentos', 'Documentos do Paciente', 'export', 'Atendimento / Prontuário • Documentos do Paciente • Exportar', 74),
  ('perm-agenda-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'agenda', 'Agenda', 'view', 'Atendimento / Prontuário • Agenda • Ver', 75),
  ('perm-agenda-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'agenda', 'Agenda', 'create', 'Atendimento / Prontuário • Agenda • Criar', 76),
  ('perm-agenda-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'agenda', 'Agenda', 'edit', 'Atendimento / Prontuário • Agenda • Editar', 77),
  ('perm-agenda-cancel', 'atendimento_prontuario', 'Atendimento / Prontuário', 'agenda', 'Agenda', 'cancel', 'Atendimento / Prontuário • Agenda • Cancelar', 78),
  ('perm-agenda-confirm', 'atendimento_prontuario', 'Atendimento / Prontuário', 'agenda', 'Agenda', 'confirm', 'Atendimento / Prontuário • Agenda • Confirmar', 79),
  ('perm-atendimento_sala_espera-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'atendimento_sala_espera', 'Sala de Espera / Check-in', 'view', 'Atendimento / Prontuário • Sala de Espera / Check-in • Ver', 80),
  ('perm-atendimento_sala_espera-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'atendimento_sala_espera', 'Sala de Espera / Check-in', 'create', 'Atendimento / Prontuário • Sala de Espera / Check-in • Criar', 81),
  ('perm-atendimento_sala_espera-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'atendimento_sala_espera', 'Sala de Espera / Check-in', 'edit', 'Atendimento / Prontuário • Sala de Espera / Check-in • Editar', 82),
  ('perm-atendimento_sala_espera-finish', 'atendimento_prontuario', 'Atendimento / Prontuário', 'atendimento_sala_espera', 'Sala de Espera / Check-in', 'finish', 'Atendimento / Prontuário • Sala de Espera / Check-in • Finalizar', 83),
  ('perm-prontuario_dados_clinicos-view', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_dados_clinicos', 'Dados Clínicos', 'view', 'Atendimento / Prontuário • Dados Clínicos • Ver', 84),
  ('perm-prontuario_dados_clinicos-create', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_dados_clinicos', 'Dados Clínicos', 'create', 'Atendimento / Prontuário • Dados Clínicos • Criar', 85),
  ('perm-prontuario_dados_clinicos-edit', 'atendimento_prontuario', 'Atendimento / Prontuário', 'prontuario_dados_clinicos', 'Dados Clínicos', 'edit', 'Atendimento / Prontuário • Dados Clínicos • Editar', 86),
  ('perm-admin_dados_clinica-view', 'administrativo', 'Administrativo', 'admin_dados_clinica', 'Dados da Clínica', 'view', 'Administrativo • Dados da Clínica • Ver', 87),
  ('perm-admin_dados_clinica-edit', 'administrativo', 'Administrativo', 'admin_dados_clinica', 'Dados da Clínica', 'edit', 'Administrativo • Dados da Clínica • Editar', 88),
  ('perm-equipe-view', 'administrativo', 'Administrativo', 'equipe', 'Dados da Equipe', 'view', 'Administrativo • Dados da Equipe • Ver', 89),
  ('perm-equipe-create', 'administrativo', 'Administrativo', 'equipe', 'Dados da Equipe', 'create', 'Administrativo • Dados da Equipe • Criar', 90),
  ('perm-equipe-edit', 'administrativo', 'Administrativo', 'equipe', 'Dados da Equipe', 'edit', 'Administrativo • Dados da Equipe • Editar', 91),
  ('perm-equipe-deactivate', 'administrativo', 'Administrativo', 'equipe', 'Dados da Equipe', 'deactivate', 'Administrativo • Dados da Equipe • Desativar', 92),
  ('perm-equipe-delete', 'administrativo', 'Administrativo', 'equipe', 'Dados da Equipe', 'delete', 'Administrativo • Dados da Equipe • Excluir', 93),
  ('perm-configuracoes_usuarios_acessos-view', 'administrativo', 'Administrativo', 'configuracoes_usuarios_acessos', 'Usuários e Acessos', 'view', 'Administrativo • Usuários e Acessos • Ver', 94),
  ('perm-configuracoes_usuarios_acessos-create', 'administrativo', 'Administrativo', 'configuracoes_usuarios_acessos', 'Usuários e Acessos', 'create', 'Administrativo • Usuários e Acessos • Criar', 95),
  ('perm-configuracoes_usuarios_acessos-edit', 'administrativo', 'Administrativo', 'configuracoes_usuarios_acessos', 'Usuários e Acessos', 'edit', 'Administrativo • Usuários e Acessos • Editar', 96),
  ('perm-configuracoes_usuarios_acessos-deactivate', 'administrativo', 'Administrativo', 'configuracoes_usuarios_acessos', 'Usuários e Acessos', 'deactivate', 'Administrativo • Usuários e Acessos • Desativar', 97),
  ('perm-configuracoes_usuarios_acessos-resend', 'administrativo', 'Administrativo', 'configuracoes_usuarios_acessos', 'Usuários e Acessos', 'resend', 'Administrativo • Usuários e Acessos • Reenviar', 98),
  ('perm-admin_base_precos_procedimentos-view', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'view', 'Administrativo • Base de Preços e Procedimentos • Ver', 99),
  ('perm-admin_base_precos_procedimentos-create', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'create', 'Administrativo • Base de Preços e Procedimentos • Criar', 100),
  ('perm-admin_base_precos_procedimentos-edit', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'edit', 'Administrativo • Base de Preços e Procedimentos • Editar', 101),
  ('perm-admin_base_precos_procedimentos-delete', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'delete', 'Administrativo • Base de Preços e Procedimentos • Excluir', 102),
  ('perm-admin_base_precos_procedimentos-import', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'import', 'Administrativo • Base de Preços e Procedimentos • Importar', 103),
  ('perm-admin_base_precos_procedimentos-export', 'administrativo', 'Administrativo', 'admin_base_precos_procedimentos', 'Base de Preços e Procedimentos', 'export', 'Administrativo • Base de Preços e Procedimentos • Exportar', 104),
  ('perm-admin_contratos-view', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'view', 'Administrativo • Contratos e Consentimentos • Ver', 105),
  ('perm-admin_contratos-create', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'create', 'Administrativo • Contratos e Consentimentos • Criar', 106),
  ('perm-admin_contratos-edit', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'edit', 'Administrativo • Contratos e Consentimentos • Editar', 107),
  ('perm-admin_contratos-delete', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'delete', 'Administrativo • Contratos e Consentimentos • Excluir', 108),
  ('perm-admin_contratos-update_template', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'update_template', 'Administrativo • Contratos e Consentimentos • Editar modelo', 109),
  ('perm-admin_contratos-generate', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'generate', 'Administrativo • Contratos e Consentimentos • Gerar contrato', 110),
  ('perm-admin_contratos-print', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'print', 'Administrativo • Contratos e Consentimentos • Imprimir', 111),
  ('perm-admin_contratos-export_pdf', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'export_pdf', 'Administrativo • Contratos e Consentimentos • Exportar PDF', 112),
  ('perm-admin_contratos-cancel', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'cancel', 'Administrativo • Contratos e Consentimentos • Cancelar', 113),
  ('perm-admin_contratos-view_audit', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'view_audit', 'Administrativo • Contratos e Consentimentos • Ver auditoria', 114),
  ('perm-admin_contratos-edit_system_clause', 'administrativo', 'Administrativo', 'admin_contratos', 'Contratos e Consentimentos', 'edit_system_clause', 'Administrativo • Contratos e Consentimentos • Editar cláusula padrão', 115),
  ('perm-admin_consentimentos-view', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'view', 'Administrativo • Consentimentos • Ver', 116),
  ('perm-admin_consentimentos-create', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'create', 'Administrativo • Consentimentos • Criar', 117),
  ('perm-admin_consentimentos-edit', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'edit', 'Administrativo • Consentimentos • Editar', 118),
  ('perm-admin_consentimentos-delete', 'administrativo', 'Administrativo', 'admin_consentimentos', 'Consentimentos', 'delete', 'Administrativo • Consentimentos • Excluir', 119),
  ('perm-configuracoes-view', 'administrativo', 'Administrativo', 'configuracoes', 'Configurações (Geral)', 'view', 'Administrativo • Configurações (Geral) • Ver', 120),
  ('perm-configuracoes-edit', 'administrativo', 'Administrativo', 'configuracoes', 'Configurações (Geral)', 'edit', 'Administrativo • Configurações (Geral) • Editar', 121),
  ('perm-financeiro_contas_receber-view', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'view', 'Financeiro • Contas a Receber • Ver', 122),
  ('perm-financeiro_contas_receber-create', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'create', 'Financeiro • Contas a Receber • Criar', 123),
  ('perm-financeiro_contas_receber-edit', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'edit', 'Financeiro • Contas a Receber • Editar', 124),
  ('perm-financeiro_contas_receber-download', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'download', 'Financeiro • Contas a Receber • Baixar', 125),
  ('perm-financeiro_contas_receber-delete', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'delete', 'Financeiro • Contas a Receber • Excluir', 126),
  ('perm-financeiro_contas_receber-export', 'financeiro', 'Financeiro', 'financeiro_contas_receber', 'Contas a Receber', 'export', 'Financeiro • Contas a Receber • Exportar', 127),
  ('perm-financeiro_contas_pagar-view', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'view', 'Financeiro • Contas a Pagar • Ver', 128),
  ('perm-financeiro_contas_pagar-create', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'create', 'Financeiro • Contas a Pagar • Criar', 129),
  ('perm-financeiro_contas_pagar-edit', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'edit', 'Financeiro • Contas a Pagar • Editar', 130),
  ('perm-financeiro_contas_pagar-download', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'download', 'Financeiro • Contas a Pagar • Baixar', 131),
  ('perm-financeiro_contas_pagar-delete', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'delete', 'Financeiro • Contas a Pagar • Excluir', 132),
  ('perm-financeiro_contas_pagar-export', 'financeiro', 'Financeiro', 'financeiro_contas_pagar', 'Contas a Pagar', 'export', 'Financeiro • Contas a Pagar • Exportar', 133),
  ('perm-financeiro_caixa-view', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'view', 'Financeiro • Caixa • Ver', 134),
  ('perm-financeiro_caixa-open', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'open', 'Financeiro • Caixa • Abrir', 135),
  ('perm-financeiro_caixa-close', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'close', 'Financeiro • Caixa • Fechar', 136),
  ('perm-financeiro_caixa-launch', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'launch', 'Financeiro • Caixa • Lançar', 137),
  ('perm-financeiro_caixa-reverse', 'financeiro', 'Financeiro', 'financeiro_caixa', 'Caixa', 'reverse', 'Financeiro • Caixa • Estornar', 138),
  ('perm-financeiro_boletos-view', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'view', 'Financeiro • Boletos/Cobranças • Ver', 139),
  ('perm-financeiro_boletos-create', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'create', 'Financeiro • Boletos/Cobranças • Criar', 140),
  ('perm-financeiro_boletos-issue', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'issue', 'Financeiro • Boletos/Cobranças • Emitir', 141),
  ('perm-financeiro_boletos-cancel', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'cancel', 'Financeiro • Boletos/Cobranças • Cancelar', 142),
  ('perm-financeiro_boletos-resend', 'financeiro', 'Financeiro', 'financeiro_boletos', 'Boletos/Cobranças', 'resend', 'Financeiro • Boletos/Cobranças • Reenviar', 143),
  ('perm-financeiro_financiamentos-view', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'view', 'Financeiro • Financiamentos • Ver', 144),
  ('perm-financeiro_financiamentos-create', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'create', 'Financeiro • Financiamentos • Criar', 145),
  ('perm-financeiro_financiamentos-edit', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'edit', 'Financeiro • Financiamentos • Editar', 146),
  ('perm-financeiro_financiamentos-approve', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'approve', 'Financeiro • Financiamentos • Aprovar', 147),
  ('perm-financeiro_financiamentos-cancel', 'financeiro', 'Financeiro', 'financeiro_financiamentos', 'Financiamentos', 'cancel', 'Financeiro • Financiamentos • Cancelar', 148),
  ('perm-financeiro_comissoes-view', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'view', 'Financeiro • Comissões • Ver', 149),
  ('perm-financeiro_comissoes-create', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'create', 'Financeiro • Comissões • Criar', 150),
  ('perm-financeiro_comissoes-edit', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'edit', 'Financeiro • Comissões • Editar', 151),
  ('perm-financeiro_comissoes-approve', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'approve', 'Financeiro • Comissões • Aprovar', 152),
  ('perm-financeiro_comissoes-export', 'financeiro', 'Financeiro', 'financeiro_comissoes', 'Comissões', 'export', 'Financeiro • Comissões • Exportar', 153),
  ('perm-financeiro_dre-view', 'financeiro', 'Financeiro', 'financeiro_dre', 'DRE / Central de Análise', 'view', 'Financeiro • DRE / Central de Análise • Ver', 154),
  ('perm-financeiro_dre-export', 'financeiro', 'Financeiro', 'financeiro_dre', 'DRE / Central de Análise', 'export', 'Financeiro • DRE / Central de Análise • Exportar', 155),
  ('perm-financeiro_relatorios-view', 'financeiro', 'Financeiro', 'financeiro_relatorios', 'Relatórios Financeiros', 'view', 'Financeiro • Relatórios Financeiros • Ver', 156),
  ('perm-financeiro_relatorios-export', 'financeiro', 'Financeiro', 'financeiro_relatorios', 'Relatórios Financeiros', 'export', 'Financeiro • Relatórios Financeiros • Exportar', 157),
  ('perm-dashboard-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'dashboard', 'Dashboard Geral', 'view', 'Dashboard / Relatórios • Dashboard Geral • Ver', 158),
  ('perm-dashboard_indicadores-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'dashboard_indicadores', 'Indicadores Principais', 'view', 'Dashboard / Relatórios • Indicadores Principais • Ver', 159),
  ('perm-relatorios_gerenciais-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_gerenciais', 'Relatórios Gerenciais', 'view', 'Dashboard / Relatórios • Relatórios Gerenciais • Ver', 160),
  ('perm-relatorios_gerenciais-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_gerenciais', 'Relatórios Gerenciais', 'export', 'Dashboard / Relatórios • Relatórios Gerenciais • Exportar', 161),
  ('perm-relatorios_atendimento-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_atendimento', 'Relatórios de Atendimento', 'view', 'Dashboard / Relatórios • Relatórios de Atendimento • Ver', 162),
  ('perm-relatorios_atendimento-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_atendimento', 'Relatórios de Atendimento', 'export', 'Dashboard / Relatórios • Relatórios de Atendimento • Exportar', 163),
  ('perm-relatorios_comerciais-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_comerciais', 'Relatórios Comerciais', 'view', 'Dashboard / Relatórios • Relatórios Comerciais • Ver', 164),
  ('perm-relatorios_comerciais-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios_comerciais', 'Relatórios Comerciais', 'export', 'Dashboard / Relatórios • Relatórios Comerciais • Exportar', 165),
  ('perm-relatorios-view', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios', 'Relatórios Financeiros', 'view', 'Dashboard / Relatórios • Relatórios Financeiros • Ver', 166),
  ('perm-relatorios-export', 'dashboard_relatorios', 'Dashboard / Relatórios', 'relatorios', 'Relatórios Financeiros', 'export', 'Dashboard / Relatórios • Relatórios Financeiros • Exportar', 167),
  ('perm-sistema_integracoes-view', 'config_sistema', 'Configurações / Sistema', 'sistema_integracoes', 'Integrações', 'view', 'Configurações / Sistema • Integrações • Ver', 168),
  ('perm-sistema_integracoes-configure', 'config_sistema', 'Configurações / Sistema', 'sistema_integracoes', 'Integrações', 'configure', 'Configurações / Sistema • Integrações • Configurar', 169),
  ('perm-sistema_whatsapp-view', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'view', 'Configurações / Sistema • WhatsApp • Ver', 170),
  ('perm-sistema_whatsapp-configure', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'configure', 'Configurações / Sistema • WhatsApp • Configurar', 171),
  ('perm-sistema_whatsapp-connect', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'connect', 'Configurações / Sistema • WhatsApp • Conectar', 172),
  ('perm-sistema_whatsapp-disconnect', 'config_sistema', 'Configurações / Sistema', 'sistema_whatsapp', 'WhatsApp', 'disconnect', 'Configurações / Sistema • WhatsApp • Desconectar', 173),
  ('perm-sistema_suporte-view', 'config_sistema', 'Configurações / Sistema', 'sistema_suporte', 'Suporte', 'view', 'Configurações / Sistema • Suporte • Ver', 174),
  ('perm-sistema_suporte-create_ticket', 'config_sistema', 'Configurações / Sistema', 'sistema_suporte', 'Suporte', 'create_ticket', 'Configurações / Sistema • Suporte • Criar chamado', 175),
  ('perm-sistema_logs_auditoria-view', 'config_sistema', 'Configurações / Sistema', 'sistema_logs_auditoria', 'Logs/Auditoria', 'view', 'Configurações / Sistema • Logs/Auditoria • Ver', 176),
  ('perm-sistema_logs_auditoria-export', 'config_sistema', 'Configurações / Sistema', 'sistema_logs_auditoria', 'Logs/Auditoria', 'export', 'Configurações / Sistema • Logs/Auditoria • Exportar', 177),
  ('perm-sistema_preferencias-view', 'config_sistema', 'Configurações / Sistema', 'sistema_preferencias', 'Preferências do Sistema', 'view', 'Configurações / Sistema • Preferências do Sistema • Ver', 178),
  ('perm-sistema_preferencias-edit', 'config_sistema', 'Configurações / Sistema', 'sistema_preferencias', 'Preferências do Sistema', 'edit', 'Configurações / Sistema • Preferências do Sistema • Editar', 179),
  ('perm-estoque-view', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'view', 'Configurações / Sistema • Estoque / Materiais • Ver', 180),
  ('perm-estoque-create', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'create', 'Configurações / Sistema • Estoque / Materiais • Criar', 181),
  ('perm-estoque-edit', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'edit', 'Configurações / Sistema • Estoque / Materiais • Editar', 182),
  ('perm-estoque-delete', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'delete', 'Configurações / Sistema • Estoque / Materiais • Excluir', 183),
  ('perm-estoque-export', 'config_sistema', 'Configurações / Sistema', 'estoque', 'Estoque / Materiais', 'export', 'Configurações / Sistema • Estoque / Materiais • Exportar', 184)
on conflict (id) do update set
  module_group_key = excluded.module_group_key,
  module_group_label = excluded.module_group_label,
  module_key = excluded.module_key,
  module_label = excluded.module_label,
  action_key = excluded.action_key,
  description = excluded.description,
  sort_order = excluded.sort_order,
  updated_at = now();

insert into public.role_permission_defaults (role_slug, permission_id)
values
  ('administrativo', 'perm-dashboard-view'),
  ('administrativo', 'perm-equipe-view'),
  ('administrativo', 'perm-equipe-create'),
  ('administrativo', 'perm-equipe-edit'),
  ('administrativo', 'perm-configuracoes_usuarios_acessos-view'),
  ('administrativo', 'perm-patients-view'),
  ('administrativo', 'perm-patients-create'),
  ('administrativo', 'perm-patients-edit'),
  ('administrativo', 'perm-agenda-view'),
  ('administrativo', 'perm-agenda-create'),
  ('administrativo', 'perm-agenda-edit'),
  ('administrativo', 'perm-prontuario_documentos-view'),
  ('administrativo', 'perm-prontuario_documentos-export'),
  ('administrativo', 'perm-admin_contratos-view'),
  ('administrativo', 'perm-admin_contratos-create'),
  ('administrativo', 'perm-admin_contratos-edit'),
  ('administrativo', 'perm-admin_contratos-delete'),
  ('administrativo', 'perm-admin_contratos-update_template'),
  ('administrativo', 'perm-admin_contratos-generate'),
  ('administrativo', 'perm-admin_contratos-print'),
  ('administrativo', 'perm-admin_contratos-export_pdf'),
  ('administrativo', 'perm-admin_contratos-cancel'),
  ('administrativo', 'perm-admin_contratos-view_audit'),
  ('administrativo', 'perm-admin_contratos-edit_system_clause'),
  ('administrativo', 'perm-prontuario_guia_clinico-view'),
  ('administrativo', 'perm-prontuario_guia_clinico-create'),
  ('administrativo', 'perm-prontuario_guia_clinico-edit'),
  ('administrativo', 'perm-prontuario_guia_clinico-delete'),
  ('comercial', 'perm-dashboard-view'),
  ('comercial', 'perm-pipeline_crm-view'),
  ('comercial', 'perm-pipeline_crm-create'),
  ('comercial', 'perm-pipeline_crm-edit'),
  ('comercial', 'perm-patients-view'),
  ('comercial', 'perm-prontuario_orcamentos-view'),
  ('comercial', 'perm-prontuario_orcamentos-create'),
  ('comercial', 'perm-prontuario_guia_clinico-view'),
  ('comercial', 'perm-admin_contratos-generate'),
  ('comercial', 'perm-admin_contratos-view'),
  ('financeiro', 'perm-dashboard-view'),
  ('financeiro', 'perm-financeiro_contas_receber-view'),
  ('financeiro', 'perm-financeiro_contas_receber-create'),
  ('financeiro', 'perm-financeiro_contas_receber-edit'),
  ('financeiro', 'perm-financeiro_contas_receber-export'),
  ('financeiro', 'perm-financeiro_contas_pagar-view'),
  ('financeiro', 'perm-financeiro_contas_pagar-create'),
  ('financeiro', 'perm-financeiro_contas_pagar-edit'),
  ('financeiro', 'perm-financeiro_contas_pagar-export'),
  ('financeiro', 'perm-financeiro_caixa-view'),
  ('financeiro', 'perm-financeiro_relatorios-view'),
  ('financeiro', 'perm-financeiro_relatorios-export'),
  ('financeiro', 'perm-prontuario_contratos-view'),
  ('atendimento', 'perm-dashboard-view'),
  ('atendimento', 'perm-agenda-view'),
  ('atendimento', 'perm-agenda-create'),
  ('atendimento', 'perm-agenda-edit'),
  ('atendimento', 'perm-patients-view'),
  ('atendimento', 'perm-patients-edit'),
  ('atendimento', 'perm-prontuario_atendimento-view'),
  ('atendimento', 'perm-prontuario_atendimento-create'),
  ('atendimento', 'perm-prontuario_atendimento-edit'),
  ('atendimento', 'perm-prontuario_documentos-view'),
  ('dentista', 'perm-dashboard-view'),
  ('dentista', 'perm-patients-view'),
  ('dentista', 'perm-agenda-view'),
  ('dentista', 'perm-prontuario_atendimento-view'),
  ('dentista', 'perm-prontuario_atendimento-create'),
  ('dentista', 'perm-prontuario_atendimento-edit'),
  ('dentista', 'perm-prontuario_planejamento-view'),
  ('dentista', 'perm-prontuario_planejamento-create'),
  ('dentista', 'perm-prontuario_planejamento-edit'),
  ('dentista', 'perm-prontuario_procedimentos-view'),
  ('dentista', 'perm-prontuario_procedimentos-create'),
  ('dentista', 'perm-prontuario_procedimentos-edit'),
  ('dentista', 'perm-prontuario_orcamentos-view'),
  ('dentista', 'perm-prontuario_guia_clinico-view'),
  ('dentista', 'perm-prontuario_guia_clinico-create'),
  ('dentista', 'perm-prontuario_guia_clinico-edit'),
  ('dentista', 'perm-prontuario_contratos-view'),
  ('dentista', 'perm-prontuario_contratos-create'),
  ('dentista', 'perm-admin_contratos-generate'),
  ('dentista', 'perm-prontuario_documentos-view'),
  ('dentista', 'perm-prontuario_dados_clinicos-view'),
  ('dentista', 'perm-prontuario_dados_clinicos-create'),
  ('dentista', 'perm-prontuario_dados_clinicos-edit'),
  ('recepcao', 'perm-dashboard-view'),
  ('recepcao', 'perm-agenda-view'),
  ('recepcao', 'perm-agenda-create'),
  ('recepcao', 'perm-agenda-edit'),
  ('recepcao', 'perm-patients-view'),
  ('recepcao', 'perm-patients-edit'),
  ('recepcao', 'perm-prontuario_atendimento-view'),
  ('recepcao', 'perm-prontuario_atendimento-create'),
  ('recepcao', 'perm-prontuario_atendimento-edit'),
  ('recepcao', 'perm-prontuario_documentos-view'),
  ('profissional', 'perm-dashboard-view'),
  ('profissional', 'perm-patients-view'),
  ('profissional', 'perm-agenda-view'),
  ('profissional', 'perm-prontuario_atendimento-view'),
  ('profissional', 'perm-prontuario_atendimento-create'),
  ('profissional', 'perm-prontuario_atendimento-edit'),
  ('profissional', 'perm-prontuario_planejamento-view'),
  ('profissional', 'perm-prontuario_planejamento-create'),
  ('profissional', 'perm-prontuario_planejamento-edit'),
  ('profissional', 'perm-prontuario_procedimentos-view'),
  ('profissional', 'perm-prontuario_procedimentos-create'),
  ('profissional', 'perm-prontuario_procedimentos-edit'),
  ('profissional', 'perm-prontuario_orcamentos-view'),
  ('profissional', 'perm-prontuario_guia_clinico-view'),
  ('profissional', 'perm-prontuario_guia_clinico-create'),
  ('profissional', 'perm-prontuario_guia_clinico-edit'),
  ('profissional', 'perm-prontuario_contratos-view'),
  ('profissional', 'perm-prontuario_contratos-create'),
  ('profissional', 'perm-admin_contratos-generate'),
  ('profissional', 'perm-prontuario_documentos-view'),
  ('profissional', 'perm-prontuario_dados_clinicos-view'),
  ('profissional', 'perm-prontuario_dados_clinicos-create'),
  ('profissional', 'perm-prontuario_dados_clinicos-edit'),
  ('gerente', 'perm-dashboard-view'),
  ('gerente', 'perm-equipe-view'),
  ('gerente', 'perm-equipe-create'),
  ('gerente', 'perm-equipe-edit'),
  ('gerente', 'perm-configuracoes_usuarios_acessos-view'),
  ('gerente', 'perm-patients-view'),
  ('gerente', 'perm-patients-create'),
  ('gerente', 'perm-patients-edit'),
  ('gerente', 'perm-agenda-view'),
  ('gerente', 'perm-agenda-create'),
  ('gerente', 'perm-agenda-edit'),
  ('gerente', 'perm-prontuario_documentos-view'),
  ('gerente', 'perm-prontuario_documentos-export'),
  ('gerente', 'perm-admin_contratos-view'),
  ('gerente', 'perm-admin_contratos-create'),
  ('gerente', 'perm-admin_contratos-edit'),
  ('gerente', 'perm-admin_contratos-delete'),
  ('gerente', 'perm-admin_contratos-update_template'),
  ('gerente', 'perm-admin_contratos-generate'),
  ('gerente', 'perm-admin_contratos-print'),
  ('gerente', 'perm-admin_contratos-export_pdf'),
  ('gerente', 'perm-admin_contratos-cancel'),
  ('gerente', 'perm-admin_contratos-view_audit'),
  ('gerente', 'perm-admin_contratos-edit_system_clause'),
  ('gerente', 'perm-prontuario_guia_clinico-view'),
  ('gerente', 'perm-prontuario_guia_clinico-create'),
  ('gerente', 'perm-prontuario_guia_clinico-edit'),
  ('gerente', 'perm-prontuario_guia_clinico-delete'),
  ('owner', 'perm-dashboard-view'),
  ('owner', 'perm-agenda-view'),
  ('owner', 'perm-agenda-create'),
  ('owner', 'perm-agenda-edit'),
  ('owner', 'perm-patients-view'),
  ('owner', 'perm-patients-edit'),
  ('owner', 'perm-prontuario_atendimento-view'),
  ('owner', 'perm-prontuario_atendimento-create'),
  ('owner', 'perm-prontuario_atendimento-edit'),
  ('owner', 'perm-prontuario_documentos-view'),
  ('admin', 'perm-dashboard-view'),
  ('admin', 'perm-agenda-view'),
  ('admin', 'perm-agenda-create'),
  ('admin', 'perm-agenda-edit'),
  ('admin', 'perm-patients-view'),
  ('admin', 'perm-patients-edit'),
  ('admin', 'perm-prontuario_atendimento-view'),
  ('admin', 'perm-prontuario_atendimento-create'),
  ('admin', 'perm-prontuario_atendimento-edit'),
  ('admin', 'perm-prontuario_documentos-view'),
  ('master', 'perm-dashboard-view'),
  ('master', 'perm-agenda-view'),
  ('master', 'perm-agenda-create'),
  ('master', 'perm-agenda-edit'),
  ('master', 'perm-patients-view'),
  ('master', 'perm-patients-edit'),
  ('master', 'perm-prontuario_atendimento-view'),
  ('master', 'perm-prontuario_atendimento-create'),
  ('master', 'perm-prontuario_atendimento-edit'),
  ('master', 'perm-prontuario_documentos-view')
on conflict (role_slug, permission_id) do nothing;
